import { v4 as uuid } from 'uuid';

export const userMock = {
  id: 'main-user-id',
  avatar: '/icons/cat_icon_1.png',
  name: 'Игорь',
  surname: 'Весёлкин',
  userName: 'funny_igor_007',
  email: 'igor.veselkin@example.com',
  phone: '+7 (999) 123-45-67',
};

export const contactsMock = [
  {
    chatId: 'chat-1a2b3c4d-0001',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Гении продуктивности',
    name: 'Михаил Гиперответственный',
    userName: 'workaholic_mike',
    tags: ['работа', 'душнила'],
  },
  {
    chatId: 'chat-1a2b3c4d-0002',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Мемологи-аналитики',
    name: 'Анастасия Ржунемогу',
    userName: 'memer_nastia',
    tags: ['поржать'],
  },
  {
    chatId: 'chat-1a2b3c4d-0003',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Семейная опера',
    name: 'Тётя Галя',
    userName: 'aunt_galya',
    tags: ['семья'],
  },
  {
    chatId: 'chat-1a2b3c4d-0004',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Свиданки и булочки',
    name: 'Серёжа Романтик',
    userName: 'tinder_serge',
    tags: ['тиндер'],
  },
  {
    chatId: 'chat-1a2b3c4d-0005',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Разбор полётов',
    name: 'Влад Занудов',
    userName: 'vladislav_zzz',
    tags: ['душнила', 'работа'],
  },
  {
    chatId: 'chat-1a2b3c4d-0006',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Хто ты вообще?',
    name: 'Таинственный Хомяк',
    userName: 'unknown_hamster',
    tags: ['кто_это'],
  },
  {
    chatId: 'chat-1a2b3c4d-0007',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Юмор из 2007',
    name: 'Славик Шутканул',
    userName: 'slavik_mem',
    tags: ['поржать', 'семья'],
  },
  {
    chatId: 'chat-1a2b3c4d-0008',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Котики и дедлайны',
    name: 'Катя ВсёУспею',
    userName: 'katya_rush',
    tags: ['работа', 'семья'],
  }
];


export function generateMessages(contact: { chatId: string }) {
  const messages = [
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Привет! Ты слышал, что коты тайно управляют интернетом?",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Ну конечно, у меня дома целый штаб хвостатых агентов!",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Ха-ха, представляешь, если они начнут диктовать нам правила? 'Все должны спать по 18 часов!'",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Ага, и обязательный режим ласк и кормежек по первому требованию!",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Вот так и живём, в эпоху кошачьей диктатуры.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Кстати, ты видел, как они на тебя смотрят, будто читают мысли?",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "О, да! Иногда кажется, что они понимают меня лучше, чем люди.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Пожалуй, стоит присмотреться к этому внимательнее.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Ха, а что если они тайно записывают наши разговоры?",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Тогда у меня есть секрет — я не очень люблю брокколи.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Не волнуйся, я тоже держу это в тайне.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Уф, хорошо, что у нас есть общий язык — кошачий, конечно!",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Согласен! В следующий раз надо пригласить их на чай.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Только чтобы угощение было вкусным — у кошек ведь изысканный вкус.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Точно! А еще лучше — мышиные печенья!",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "О, это будет хит сезона!",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Главное, чтобы никто из них не забыл выключить лазерную указку.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Ха-ха, лазерный бой — любимое развлечение!",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Ну что, договорились — устроим кошачью вечеринку?",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Договорились! Приглашай всех пушистиков.",
    },
  ];

  return messages;
}
