import { v4 as uuid } from 'uuid';

export const userMockRus = {
  id: 'main-user-id',
  avatar: '/icons/cat_icon_1.png',
  name: 'Игорь',
  surname: 'Весёлкин',
  userName: 'funny_igor_007',
  email: 'igor.veselkin@example.com',
  phone: '+7 (999) 123-45-67',
};

export const userMock = {
  id: 'main-user-id',
  avatar: '/icons/cat_icon_1.png',
  name: 'Paco',
  surname: 'Risitas',
  userName: 'paco_risas_007',
  email: 'paco.risitas@example.com',
  phone: '+34 612 345 678',
};

export const contactsMockRus = [
  {
    chatId: 'chat-1a2b3c4d-0001',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Гении продуктивности',
    name: 'Михаил Гиперответственный',
    userName: 'workaholic_mike',
    tags: ['работа', 'душнила'],
  },
  {
    chatId: 'chat-1a2b3c4d-0002',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Мемологи-аналитики',
    name: 'Анастасия Ржунемогу',
    userName: 'memer_nastia',
    tags: ['поржать'],
  },
  {
    chatId: 'chat-1a2b3c4d-0003',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Семейная опера',
    name: 'Тётя Галя',
    userName: 'aunt_galya',
    tags: ['семья'],
  },
  {
    chatId: 'chat-1a2b3c4d-0004',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Свиданки и булочки',
    name: 'Серёжа Романтик',
    userName: 'tinder_serge',
    tags: ['тиндер'],
  },
  {
    chatId: 'chat-1a2b3c4d-0005',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Разбор полётов',
    name: 'Влад Занудов',
    userName: 'vladislav_zzz',
    tags: ['душнила', 'работа'],
  },
  {
    chatId: 'chat-1a2b3c4d-0006',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Хто ты вообще?',
    name: 'Таинственный Хомяк',
    userName: 'unknown_hamster',
    tags: ['кто_это'],
  },
  {
    chatId: 'chat-1a2b3c4d-0007',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Юмор из 2007',
    name: 'Славик Шутканул',
    userName: 'slavik_mem',
    tags: ['поржать', 'семья'],
  },
  {
    chatId: 'chat-1a2b3c4d-0008',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Котики и дедлайны',
    name: 'Катя ВсёУспею',
    userName: 'katya_rush',
    tags: ['работа', 'семья'],
  }
];

export const contactsMock = [
  {
    chatId: 'chat-es-0001',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Genios de la productividad',
    name: 'Miguel Responsable',
    userName: 'trabajo_miguel',
    tags: ['trabajo', 'pesado'],
  },
  {
    chatId: 'chat-es-0002',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Memólogos analíticos',
    name: 'Ana MeParto',
    userName: 'memes_ana',
    tags: ['reírse'],
  },
  {
    chatId: 'chat-es-0003',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Telenovela familiar',
    name: 'Tía Carmen',
    userName: 'tia_carmen',
    tags: ['familia', 'opiniones'],
  },
  {
    chatId: 'chat-es-0004',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Citas y croissants',
    name: 'Sergio Romántico',
    userName: 'tinder_sergio',
    tags: ['tinder', 'reírse'],
  },
  {
    chatId: 'chat-es-0005',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Informe de vuelo',
    name: 'Vlad el Pesado',
    userName: 'vlad_aburre',
    tags: ['pesado', 'trabajo'],
  },
  {
    chatId: 'chat-es-0006',
    avatar: '/icons/cat_icon_2.png',
    chatName: '¿Y este quién es?',
    name: 'Hámster Misterioso',
    userName: 'hamster_desconocido',
    tags: ['quién_es'],
  },
  {
    chatId: 'chat-es-0007',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Humor del 2007',
    name: 'Chusco Slavo',
    userName: 'slavo_memes',
    tags: ['reírse', 'familia', 'tinder'],
  },
  {
    chatId: 'chat-es-0008',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Gatitos y entregas',
    name: 'Cata TodoListo',
    userName: 'cata_apura',
    tags: ['trabajo', 'familia'],
  },
  {
    chatId: 'chat-es-0009',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Discusión infinita',
    name: 'José El Pesado',
    userName: 'jose_blabla',
    tags: ['pesado', 'opiniones'],
  },
  {
    chatId: 'chat-es-0010',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Dramáticos pero simpáticos',
    name: 'Lucía QuéDrama',
    userName: 'lucia_teatro',
    tags: ['opiniones', 'familia', 'reírse'],
  },
  {
    chatId: 'chat-es-0011',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Control total',
    name: 'Doña CheckList',
    userName: 'control_freak',
    tags: ['trabajo'],
  },
  {
    chatId: 'chat-es-0012',
    avatar: '/icons/cat_icon_2.png',
    chatName: 'Stickerlandia',
    name: 'Carlos Sticker',
    userName: 'emoji_rey',
    tags: ['reírse', 'familia'],
  }
];



export function generateMessages(contact: { chatId: string }) {
  const messagesRus = [
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Привет! Ты слышал, что коты тайно управляют интернетом?",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Ну конечно, у меня дома целый штаб хвостатых агентов!",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Ха-ха, представляешь, если они начнут диктовать нам правила? 'Все должны спать по 18 часов!'",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Ага, и обязательный режим ласк и кормежек по первому требованию!",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Вот так и живём, в эпоху кошачьей диктатуры.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Кстати, ты видел, как они на тебя смотрят, будто читают мысли?",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "О, да! Иногда кажется, что они понимают меня лучше, чем люди.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Пожалуй, стоит присмотреться к этому внимательнее.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Ха, а что если они тайно записывают наши разговоры?",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Тогда у меня есть секрет — я не очень люблю брокколи.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Не волнуйся, я тоже держу это в тайне.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Уф, хорошо, что у нас есть общий язык — кошачий, конечно!",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Согласен! В следующий раз надо пригласить их на чай.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Только чтобы угощение было вкусным — у кошек ведь изысканный вкус.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Точно! А еще лучше — мышиные печенья!",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "О, это будет хит сезона!",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Главное, чтобы никто из них не забыл выключить лазерную указку.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Ха-ха, лазерный бой — любимое развлечение!",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: 'main-user-id',
      avatar: '/icons/cat_icon_1.png',
      text: "Ну что, договорились — устроим кошачью вечеринку?",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Договорились! Приглашай всех пушистиков.",
    },
  ];

  const messages = [
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: userMock.id,
      avatar: '/icons/cat_icon_1.png',
      text: "¡Hola! ¿Sabías que los gatos controlan el internet en secreto?",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Obvio, tengo un escuadrón de gatos espías en casa.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: userMock.id,
      avatar: '/icons/cat_icon_1.png',
      text: "Imagínate si imponen reglas: ¡Dormir 18 horas al día obligatorio!",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Y caricias ilimitadas a cualquier hora, por supuesto.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: userMock.id,
      avatar: '/icons/cat_icon_1.png',
      text: "Vivimos en la dictadura felina y nadie lo nota.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "¿Viste cómo te miran? Como si supieran tus secretos más profundos.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: userMock.id,
      avatar: '/icons/cat_icon_1.png',
      text: "A veces creo que entienden mejor que los humanos.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Quizás deberíamos empezar a aprender su idioma... miau.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: userMock.id,
      avatar: '/icons/cat_icon_1.png',
      text: "¿Y si graban nuestras conversaciones para chantajearnos luego?",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Confesión: no me gusta el brócoli. ¡No se lo digas a nadie!",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: userMock.id,
      avatar: '/icons/cat_icon_1.png',
      text: "Tranquilo, tu secreto está a salvo conmigo. Y con los gatos.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Lo importante es que todos hablamos el idioma felino.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: userMock.id,
      avatar: '/icons/cat_icon_1.png',
      text: "Tenemos que invitarlos a tomar té... o leche.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Pero con snacks gourmet. Los gatos tienen paladar fino.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: userMock.id,
      avatar: '/icons/cat_icon_1.png',
      text: "¡Galletas de ratón! Eso sí que sería un manjar.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "¡El próximo hit culinario del año!",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: userMock.id,
      avatar: '/icons/cat_icon_1.png',
      text: "Solo asegúrate de apagar el puntero láser antes de dormir.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "Batalla láser nocturna: el clásico preferido.",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: userMock.id,
      avatar: '/icons/cat_icon_1.png',
      text: "Entonces... ¿hacemos una fiesta felina?",
    },
    {
      messageId: uuid(),
      chatId: contact.chatId,
      senderId: contact.chatId,
      avatar: '/icons/cat_icon_2.png',
      text: "¡Hecho! Invita a todos los peluditos.",
    },
  ];



  return messages;
}
